import { useMemo, useState, type FormEvent } from 'react';
import { Check, ChevronDown, Leaf, Repeat2, Trash2 } from 'lucide-react';
import { useDrip } from '../context';
import { todayISO, addDays } from '../lib/analytics';
import { addMonths, addYears, format, parseISO } from 'date-fns';
import { CategoryIcon, Sheet } from '../components/ui';
import type { Metodo, Recurrente, Registro } from '../types';
export default function Agregar({record,onClose}:{record?:Registro;onClose:()=>void}){
 const {data,saveRegistro,saveEntity,deleteRegistro,toast}=useDrip();const [kind,setKind]=useState<'gasto'|'ingreso'|'deuda'>(record?.tipo==='ingreso'?'ingreso':record?.tipo.startsWith('deuda')?'deuda':'gasto');const [amount,setAmount]=useState(record?String(record.monto):'');const [category,setCategory]=useState(record?.categoria??'');const [description,setDescription]=useState(record?.descripcion??'');const [tags,setTags]=useState(record?.tags??'');const [date,setDate]=useState(record?.fecha??todayISO());const [method,setMethod]=useState<Metodo>(record?.metodo_pago??'debito');const [necessary,setNecessary]=useState(record?.necesidad!=='innecesario');const [fixed,setFixed]=useState(record?.subtipo==='fijo');const [salary,setSalary]=useState(record?.subtipo!=='adicional');const [debtId,setDebtId]=useState(record?.deuda_id??data.deudas.find(d=>d.activa)?.id??'');const [debtPay,setDebtPay]=useState(record?.tipo!=='deuda_aumento');const [repeat,setRepeat]=useState(false);const [frequency,setFrequency]=useState<Recurrente['frecuencia']>('mensual');const [details,setDetails]=useState(Boolean(record));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirmDelete,setConfirmDelete]=useState(false);
 const categories=useMemo(()=>{const recent=[...data.registros].filter(r=>!r.eliminado).sort((a,b)=>b.creado_en.localeCompare(a.creado_en)).map(r=>r.categoria);return data.categorias.filter(c=>c.activa&&c.tipo===(kind==='ingreso'?'ingreso':'gasto')).sort((a,b)=>{const ai=recent.indexOf(a.nombre),bi=recent.indexOf(b.nombre);return (ai<0?999:ai)-(bi<0?999:bi)})},[data.categorias,data.registros,kind]);const selectedCategory=categories.some(c=>c.nombre===category)?category:categories[0]?.nombre??'';
 const existingTags=[...new Set(data.registros.flatMap(r=>r.tags.split(',')).filter(Boolean))];
 async function submit(e?:FormEvent,noSpend=false){e?.preventDefault();setError('');const value=Number(amount.replace(',','.'));if(!noSpend&&(!Number.isFinite(value)||value<=0)){setError('Escribe un monto mayor a cero.');return}if(!noSpend&&kind==='deuda'&&!debtId){setError('Primero crea una deuda en Más → Deudas.');return}setBusy(true);try{const now=new Date().toISOString();let recurrenteId=record?.recurrente_id??'';if(repeat&&kind==='gasto'&&!noSpend){recurrenteId=crypto.randomUUID();const next=frequency==='semanal'?addDays(date,7):frequency==='quincenal'?addDays(date,15):format(frequency==='mensual'?addMonths(parseISO(date),1):addYears(parseISO(date),1),'yyyy-MM-dd');await saveEntity('recurrente',{id:recurrenteId,descripcion:description||selectedCategory,monto:value,categoria:selectedCategory,tags,frecuencia:frequency,dia:Number(date.slice(-2)),proximo_pago:next,metodo_pago:method,activa:true})}await saveRegistro({id:record?.id??crypto.randomUUID(),fecha:noSpend?todayISO():date,tipo:noSpend?'sin_gasto':kind==='deuda'?(debtPay?'deuda_pago':'deuda_aumento'):kind,subtipo:noSpend||kind==='deuda'?'':kind==='ingreso'?(salary?'sueldo':'adicional'):(fixed||repeat?'fijo':'variable'),monto:noSpend?0:value,categoria:noSpend?'':kind==='deuda'?'Deudas':selectedCategory,tags:tags.toLowerCase().replaceAll('#','').split(',').map(t=>t.trim()).filter(Boolean).join(','),descripcion:noSpend?'Hoy no gasté':description,metodo_pago:method,necesidad:!noSpend&&kind==='gasto'?(necessary?'necesario':'innecesario'):'',recurrente_id:recurrenteId,deuda_id:!noSpend&&kind==='deuda'?debtId:'',creado_en:record?.creado_en??now,actualizado_en:now,eliminado:false});navigator.vibrate?.(15);toast(noSpend?'Un día más hacia tu meta. ¡Bien hecho!':record?'Movimiento actualizado':'Movimiento guardado');onClose()}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar. Inténtalo de nuevo.')}finally{setBusy(false)}}
 async function remove(){if(!record)return;setBusy(true);try{await deleteRegistro(record.id);toast('Movimiento eliminado');onClose()}catch(err){setError(err instanceof Error?err.message:'No se pudo eliminar')}finally{setBusy(false)}}
 return <Sheet title={record?'Editar movimiento':'Un nuevo movimiento'} onClose={onClose}><form onSubmit={submit} className="capture-form"><div className="segmented">{(['gasto','ingreso','deuda'] as const).map(k=><button type="button" key={k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{k==='gasto'?'Gasto':k==='ingreso'?'Ingreso':'Deuda'}</button>)}</div><label className="amount-label" htmlFor="amount">¿Cuánto {kind==='ingreso'?'recibiste':kind==='deuda'?'registramos':'gastaste'}?</label><div className="amount-input"><span>$</span><input id="amount" aria-label="Monto" autoFocus={!record} inputMode="decimal" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^\d.,]/g,''))}/><span>{data.config.moneda}</span></div>
 {kind==='deuda'?<><label>Deuda<select value={debtId} onChange={e=>setDebtId(e.target.value)}><option value="">Selecciona una deuda</option>{data.deudas.filter(d=>d.activa||d.id===debtId).map(d=><option key={d.id} value={d.id}>{d.nombre}</option>)}</select></label><div className="segmented"><button type="button" className={debtPay?'active':''} onClick={()=>setDebtPay(true)}>Abonar a deuda</button><button type="button" className={!debtPay?'active':''} onClick={()=>setDebtPay(false)}>Aumentar deuda</button></div></>:<><label className="field-heading">Categoría <small>Las recientes, primero</small></label><div className="category-grid">{categories.map(c=><button type="button" key={c.id} className={selectedCategory===c.nombre?'selected':''} onClick={()=>setCategory(c.nombre)}><CategoryIcon category={c}/><span>{c.nombre}</span></button>)}</div></>}
 {kind==='gasto'&&<div className="necessity"><span>¿Era necesario?</span><div><button type="button" aria-pressed={necessary} className={necessary?'selected':''} onClick={()=>setNecessary(true)}>Sí</button><button type="button" aria-pressed={!necessary} className={!necessary?'selected':''} onClick={()=>setNecessary(false)}>Un gusto</button></div></div>}{kind==='ingreso'&&<div className="segmented"><button type="button" className={salary?'active':''} onClick={()=>setSalary(true)}>Sueldo</button><button type="button" className={!salary?'active':''} onClick={()=>setSalary(false)}>Adicional</button></div>}
 <button className="details-toggle" type="button" onClick={()=>setDetails(!details)} aria-expanded={details}>Añadir detalles <ChevronDown size={17} style={{transform:details?'rotate(180deg)':undefined}}/></button>
 {details&&<div className="form-stack"><label>Descripción<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Por ejemplo, café camino al trabajo" maxLength={500}/></label><div className="form-two"><label>Fecha<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Método<select value={method} onChange={e=>setMethod(e.target.value as Metodo)}>{(['debito','efectivo','credito','transferencia','otro'] as const).map(m=><option key={m} value={m}>{({debito:'Débito',credito:'Crédito',efectivo:'Efectivo',transferencia:'Transferencia',otro:'Otro'})[m]}</option>)}</select></label></div><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="antojo, juntos, trabajo" list="tags"/><datalist id="tags">{existingTags.map(t=><option key={t} value={t}/>)}</datalist></label>{existingTags.length>0&&<div className="chips">{existingTags.slice(0,8).map(t=><button type="button" className="chip" key={t} onClick={()=>setTags([...new Set([...tags.split(',').filter(Boolean),t])].join(','))}>#{t}</button>)}</div>}{kind==='gasto'&&<><label className="check-field"><input type="checkbox" checked={fixed} onChange={e=>setFixed(e.target.checked)}/>Es un pago fijo</label>{!record?.recurrente_id&&<label className="check-field"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/><Repeat2 size={16}/> Repetir este pago</label>}{repeat&&<label>Frecuencia<select value={frequency} onChange={e=>setFrequency(e.target.value as Recurrente['frecuencia'])}><option value="semanal">Cada semana</option><option value="quincenal">Cada 15 días</option><option value="mensual">Cada mes</option><option value="anual">Cada año</option></select></label>}</>}</div>}
 {error&&<p className="error-message" role="alert">{error}</p>}<div className="sheet-actions"><button className="button primary full" disabled={busy} type="submit"><Check size={18}/>{busy?'Guardando…':record?'Guardar cambios':'Guardar movimiento'}</button>{!record&&<button type="button" className="button calm full" disabled={busy} onClick={()=>submit(undefined,true)}><Leaf size={17}/> Hoy no gasté</button>}{record&&(confirmDelete?<div className="delete-confirm"><p>¿Eliminar este movimiento?</p><button type="button" className="button danger" disabled={busy} onClick={remove}>Sí, eliminar</button><button type="button" className="text-button" onClick={()=>setConfirmDelete(false)}>Cancelar</button></div>:<button type="button" className="text-button danger-text full" onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>Eliminar movimiento</button>)}</div></form></Sheet>
}
